# Generated by Django 5.1 on 2024-09-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adm_no', models.IntegerField(max_length=100)),
                ('age', models.IntegerField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='images/')),
                ('kcse', models.ImageField(default='default.png', upload_to='certificates/')),
            ],
        ),
    ]
